# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/machinelearning-az.git

# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Test it

In [ ]:
!ls '/content/drive/My Drive' 

# Google colab tools

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Plantilla de Pre Procesado - Datos Categóricos


# Cómo importar las librerías


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values


# Imputar data faltante

In [3]:
from sklearn.impute import SimpleImputer

In [5]:
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean", verbose=0)
imputer = imputer.fit(X[:,1:3]) 
X[:, 1:3] = imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Codificar datos categóricos

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [8]:
# Como el pais es categorico y no tiene orden y tiene mas de dos valores primero lo pasamos a numero y luego a variables 
# dummies por el onehotencoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [14]:
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [18]:
# FORMA ACTUAL PARA CODIFICAR DATOS CATEGORICOS SIN ORDEN
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                         # Leave the rest of the columns untouched
)

In [19]:
X = np.array(ct.fit_transform(X), dtype=np.float)

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [21]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [22]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [21]:
print(X.shape)

(10, 5)


In [22]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [23]:
result = pd.DataFrame({'Column1': X[:, 0], 'Column2': X[:, 1],'Column3': X[:, 2], 'Age': X[:, 3],'Salary': X[:, 4],'Purchased': y[:]})
display(result)

Column1  Column2  Column3        Age        Salary  Purchased
0      1.0      0.0      0.0  44.000000  72000.000000          0
1      0.0      0.0      1.0  27.000000  48000.000000          1
2      0.0      1.0      0.0  30.000000  54000.000000          0
3      0.0      0.0      1.0  38.000000  61000.000000          0
4      0.0      1.0      0.0  40.000000  63777.777778          1
5      1.0      0.0      0.0  35.000000  58000.000000          1
6      0.0      0.0      1.0  38.777778  52000.000000          0
7      1.0      0.0      0.0  48.000000  79000.000000          1
8      0.0      1.0      0.0  50.000000  83000.000000          0
9      1.0      0.0      0.0  37.000000  67000.000000          1

# Dividir la data de entrenamiento y de test

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=101)

# Escalado de variables

In [26]:
#Escalado por estandarizacion
from sklearn.preprocessing import StandardScaler

In [27]:
sc_X = StandardScaler()

In [28]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [30]:
X_train

array([[-0.8660254 ,  2.44948974, -0.8660254 ,  0.40005556,  0.2668251 ],
       [ 1.15470054, -0.40824829, -0.8660254 , -0.11782458,  0.60748859],
       [-0.8660254 , -0.40824829,  1.15470054,  0.05480213, -0.02685032],
       [ 1.15470054, -0.40824829, -0.8660254 , -0.46307801, -0.34401978],
       [ 1.15470054, -0.40824829, -0.8660254 ,  1.78106926,  1.87616642],
       [-0.8660254 , -0.40824829,  1.15470054,  0.18906735, -0.9783587 ],
       [-0.8660254 , -0.40824829,  1.15470054, -1.84409171, -1.40125131]])